<a href="https://colab.research.google.com/github/anurag4667/Deep_learning/blob/main/word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

sent = ['The glass of milk',
        'the glass of juice',
        'the cup of Tea',
        'I am a good boy',
        'I am a good developer',
        'Understan the meaning of words',
        'your videos are good',]

print(sent)

voc_size = 10000

onehot_repr = [one_hot(words,voc_size) for words in sent]
print(onehot_repr)

sent_len = 8
embedded_docs = pad_sequences(onehot_repr,padding = 'pre',maxlen=sent_len)
print(embedded_docs)

dim= 10
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_len))
# build the model first
model.build(input_shape=(None, sent_len))
model.compile('adam','mse')
model.summary()

print(model.predict(embedded_docs))
print(embedded_docs[0])
print(model.predict(embedded_docs)[0])

['The glass of milk', 'the glass of juice', 'the cup of Tea', 'I am a good boy', 'I am a good developer', 'Understan the meaning of words', 'your videos are good']
[[3112, 5838, 2298, 9820], [3112, 5838, 2298, 5300], [3112, 5848, 2298, 111], [8346, 5381, 5502, 2931, 5347], [8346, 5381, 5502, 2931, 5642], [5648, 3112, 7568, 2298, 7004], [6851, 2946, 4911, 2931]]
[[   0    0    0    0 3112 5838 2298 9820]
 [   0    0    0    0 3112 5838 2298 5300]
 [   0    0    0    0 3112 5848 2298  111]
 [   0    0    0 8346 5381 5502 2931 5347]
 [   0    0    0 8346 5381 5502 2931 5642]
 [   0    0    0 5648 3112 7568 2298 7004]
 [   0    0    0    0 6851 2946 4911 2931]]


Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_13 (Embedding)        │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
[[[-0.04137348 -0.03657135  0.01329929 -0.02113031 -0.02362951
   -0.04744477 -0.02261773 -0.04555969  0.03909269  0.02121189]
  [-0.04137348 -0.03657135  0.01329929 -0.02113031 -0.02362951
   -0.04744477 -0.02261773 -0.04555969  0.03909269  0.02121189]
  [-0.04137348 -0.03657135  0.01329929 -0.02113031 -0.02362951
   -0.04744477 -0.02261773 -0.04555969  0.03909269  0.02121189]
  [-0.04137348 -0.03657135  0.01329929 -0.02113031 -0.02362951
   -0.04744477 -0.02261773 -0.04555969  0.03909269  0.02121189]
  [ 0.02512122  0.03907481  0.0460251   0.03216955 -0.00037533
    0.04180268  0.0240625   0.032313   -0.03898294  0.04129391]
  [ 0.00801704  0.01817432 -0.01128874  0.03093917 -0.01268157
   -0.02676098 -0.04900323 -0.04940696 -0.03361423 -0.04296958]
  [ 0.01711487  0.0457327   0.04324997 -0.02269466  0.02776423
   -0.01913608 -0.04051952 -0.00733592 -0.0208104   0.00454462]
  [-0.0224382  -0.00490745  0.02177674  0.03139979  0.0418957
    0.02782